# Generated by Django 5.0.6 on 2024-05-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('CountryCode', models.CharField(primary_key=True, serialize=False)),
                ('CountryName', models.CharField(max_length=50)),
            ],
        ),
    ]
