# Generated by Django 5.0.6 on 2024-05-31 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pais',
            old_name='CountryCode',
            new_name='countryCode',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='CountryName',
            new_name='countryName',
        ),
    ]
