# Generated by Django 5.0.6 on 2024-05-31 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_countrycode_pais_countrycode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pais',
            old_name='countryCode',
            new_name='countrycode',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='countryName',
            new_name='countryname',
        ),
    ]
