# Generated by Django 5.0.6 on 2024-05-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ciudad_hotel_viaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='attractions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='faxnumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotelfacilities',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotelname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotelrating',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotelwebsiteurl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='map',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phonenumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='pincode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
