# Generated by Django 5.0.6 on 2024-05-31 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_hotel_address_alter_hotel_attractions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_info',
            fields=[
                ('idhotel', models.AutoField(primary_key=True, serialize=False)),
                ('hotelcode', models.CharField(max_length=50)),
                ('hotelname', models.CharField(max_length=50)),
                ('hotelrating', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(null=True)),
                ('attractions', models.TextField(null=True)),
                ('faxnumber', models.CharField(max_length=50, null=True)),
                ('hotelfacilities', models.TextField(null=True)),
                ('map', models.CharField(max_length=100, null=True)),
                ('phonenumber', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=50, null=True)),
                ('hotelwebsiteurl', models.CharField(max_length=200, null=True)),
                ('citycode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ciudad')),
            ],
        ),
        migrations.AlterField(
            model_name='viaje',
            name='hotelcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hotel_info'),
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
