# Generated by Django 5.0.6 on 2024-06-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_hotel_info_alter_viaje_hotelcode_delete_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_info',
            name='faxnumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel_info',
            name='hotelcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel_info',
            name='hotelname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel_info',
            name='hotelrating',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel_info',
            name='pincode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
