# Generated by Django 5.0.6 on 2024-06-04 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_hotel_info_faxnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('idreseña', models.AutoField(primary_key=True, serialize=False)),
                ('hotel', models.TextField()),
                ('texto', models.TextField()),
                ('puntuacion', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('idvuelo', models.AutoField(primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha_salida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
    ]
